# Generated by Django 4.2 on 2025-03-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PC', 'Computadora'), ('MOUSE', 'Mouse'), ('TECLADO', 'Teclado'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_danio', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REPARADO', 'Reparado'), ('BAJA', 'Dado de Baja')], default='PENDIENTE', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.equipo')),
            ],
        ),
    ]
